import React from 'react';
import { ExecutiveStructuredVisual } from '../../../types';
import { cn } from '../../../lib/utils';

const palette = ['#20AEEA', '#00CE68', '#0455C9', '#014F36', '#64748B'];
const items = (visual: ExecutiveStructuredVisual) => visual.nodes?.length ? visual.nodes : visual.steps?.map((s, i) => ({ id: String(i), label: s.label, description: s.description })) || visual.cards?.map((c, i) => ({ id: String(i), label: c.title, description: c.body })) || [];

function Shell({ title, children }: { title: string; children: React.ReactNode }) {
  return <div className="h-full w-full rounded-[28px] bg-white/95 p-5 text-slate-950 shadow-[0_18px_45px_rgba(15,23,42,.14)] ring-1 ring-black/5"><div className="mb-3 text-[10px] font-black uppercase tracking-[.22em] text-slate-400">{title}</div>{children}</div>;
}

export function ExecutiveProcessFlow({ visual }: { visual: ExecutiveStructuredVisual }) {
  return <Shell title="Process flow"><div className="flex h-full items-center gap-3">{items(visual).slice(0,5).map((n, i) => <React.Fragment key={n.id || i}><div className="flex-1 rounded-2xl border p-4"><div className="text-xs font-black" style={{color:palette[i%palette.length]}}>0{i+1}</div><div className="text-sm font-black">{n.label}</div><div className="mt-1 text-xs font-semibold text-slate-500">{n.description}</div></div>{i<items(visual).length-1 && i<4 && <div className="text-2xl font-black text-slate-300">→</div>}</React.Fragment>)}</div></Shell>;
}
export function ExecutiveTimeline({ visual }: { visual: ExecutiveStructuredVisual }) { return <Shell title="Timeline"><div className="relative mt-8 flex justify-between border-t-4 border-slate-200 pt-6">{items(visual).slice(0,5).map((n,i)=><div key={n.id||i} className="w-1/5 pr-3"><div className="-mt-10 mb-4 h-5 w-5 rounded-full ring-4 ring-white" style={{background:palette[i%palette.length]}}/><div className="text-sm font-black">{n.label}</div><div className="text-xs font-semibold text-slate-500">{n.description}</div></div>)}</div></Shell>; }
export function ExecutiveDependencyMap({ visual }: { visual: ExecutiveStructuredVisual }) { return <Shell title="Dependency map"><div className="grid h-full grid-cols-3 gap-3">{items(visual).slice(0,6).map((n,i)=><div key={n.id||i} className="rounded-2xl bg-slate-50 p-4 ring-1 ring-slate-200"><div className="mb-2 h-2 w-10 rounded-full" style={{background:palette[i%palette.length]}}/><div className="text-sm font-black">{n.label}</div><div className="text-xs text-slate-500">{n.description}</div></div>)}</div></Shell>; }
export function ExecutiveRiskMatrix({ visual }: { visual: ExecutiveStructuredVisual }) { return <Shell title="Risk matrix"><div className="grid h-[90%] grid-cols-2 grid-rows-2 gap-3">{['Monitor','Mitigate','Accept','Escalate'].map((label,i)=><div key={label} className={cn('rounded-2xl p-4', i===3?'bg-red-50':'bg-slate-50')}><div className="text-xs font-black uppercase text-slate-400">{label}</div><div className="mt-3 text-sm font-black">{items(visual)[i]?.label || 'Risk area'}</div><div className="text-xs text-slate-500">{items(visual)[i]?.description}</div></div>)}</div></Shell>; }
export function ExecutiveMetricDashboard({ visual }: { visual: ExecutiveStructuredVisual }) { const m=visual.metrics?.length?visual.metrics:items(visual).map((n,i)=>({label:n.label,value:`${80-i*9}%`,description:n.description})); return <Shell title="Metric dashboard"><div className="grid h-full grid-cols-2 gap-3">{m.slice(0,4).map((x,i)=><div key={i} className="rounded-2xl bg-slate-50 p-5"><div className="text-3xl font-black" style={{color:palette[i%palette.length]}}>{x.value}</div><div className="text-sm font-black">{x.label}</div><div className="text-xs text-slate-500">{x.description}</div></div>)}</div></Shell>; }
export function ExecutiveHierarchy({ visual }: { visual: ExecutiveStructuredVisual }) { return <Shell title="Hierarchy"><div className="flex h-full flex-col items-center justify-center gap-3">{items(visual).slice(0,5).map((n,i)=><div key={n.id||i} className="rounded-2xl p-3 text-center text-sm font-black text-white" style={{background:palette[i%palette.length], width:`${95-i*12}%`}}>{n.label}</div>)}</div></Shell>; }
export function ExecutiveEcosystemMap({ visual }: { visual: ExecutiveStructuredVisual }) { return <Shell title="Ecosystem map"><div className="relative h-[92%]"><div className="absolute left-1/2 top-1/2 grid h-28 w-28 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-slate-950 text-center text-xs font-black text-white">Core model</div>{items(visual).slice(0,6).map((n,i)=><div key={n.id||i} className="absolute rounded-2xl bg-slate-50 p-3 text-xs font-bold ring-1 ring-slate-200" style={{left:`${i%2?62:8}%`,top:`${12+(i%3)*28}%`}}>{n.label}</div>)}</div></Shell>; }
export function ExecutiveComparison({ visual }: { visual: ExecutiveStructuredVisual }) { return <Shell title="Comparison"><div className="grid h-full grid-cols-2 gap-4">{items(visual).slice(0,2).map((n,i)=><div key={n.id||i} className="rounded-3xl bg-slate-50 p-5"><div className="mb-3 text-xs font-black uppercase" style={{color:palette[i]}}>{i?'Option B':'Option A'}</div><div className="text-xl font-black">{n.label}</div><div className="mt-2 text-sm font-semibold text-slate-600">{n.description}</div></div>)}</div></Shell>; }

export function ExecutiveStructuredVisualRenderer({ visual, className }: { visual?: ExecutiveStructuredVisual; className?: string }) {
  if (!visual) return null;
  const props = { visual };
  return <div className={className} data-executive-structured-visual={visual.type}>{visual.type === 'timeline' ? <ExecutiveTimeline {...props}/> : visual.type === 'dependency-map' ? <ExecutiveDependencyMap {...props}/> : visual.type === 'risk-matrix' ? <ExecutiveRiskMatrix {...props}/> : visual.type === 'metric-dashboard' ? <ExecutiveMetricDashboard {...props}/> : visual.type === 'hierarchy' ? <ExecutiveHierarchy {...props}/> : visual.type === 'ecosystem-map' ? <ExecutiveEcosystemMap {...props}/> : visual.type === 'comparison' ? <ExecutiveComparison {...props}/> : <ExecutiveProcessFlow {...props}/>}</div>;
}
