import React from 'react';
import { ExecutiveStructuredVisual } from '../../../types';
import { EXECUTIVE_PALETTES, ExecutiveDesignTokens } from '../../../lib/executiveTheme';

const items = (visual: ExecutiveStructuredVisual) => visual.nodes?.length ? visual.nodes : visual.steps?.map((s, i) => ({ id: String(i), label: s.label, description: s.description })) || visual.cards?.map((c, i) => ({ id: String(i), label: c.title, description: c.body })) || [];
const defaultTheme = EXECUTIVE_PALETTES['boardroom-light'];
const panelStyle = (theme: ExecutiveDesignTokens, emphasis?: 'risk') => ({ backgroundColor: emphasis === 'risk' ? '#FEF2F2' : theme.surfaceAlt, borderColor: emphasis === 'risk' ? theme.risk : theme.border });

function Shell({ title, children, theme = defaultTheme }: { title: string; children: React.ReactNode; theme?: ExecutiveDesignTokens }) {
  return <div className="h-full w-full rounded-[28px] p-5 ring-1" style={{ backgroundColor: theme.surface, color: '#0F172A', boxShadow: theme.shadow, borderColor: theme.border }}><div className="mb-3 text-[10px] font-black uppercase tracking-[.22em]" style={{ color: theme.mutedText }}>{title}</div>{children}</div>;
}

export function ExecutiveProcessFlow({ visual, theme = defaultTheme }: { visual: ExecutiveStructuredVisual; theme?: ExecutiveDesignTokens }) {
  const list = items(visual).slice(0, 5);
  return <Shell title="Process flow" theme={theme}><div className="flex h-full items-center gap-3">{list.map((n, i) => <React.Fragment key={n.id || i}><div className="flex-1 rounded-2xl border p-4" style={panelStyle(theme)}><div className="text-xs font-black" style={{ color: theme.chart[i % theme.chart.length] }}>0{i + 1}</div><div className="text-sm font-black">{n.label}</div><div className="mt-1 text-xs font-semibold" style={{ color: theme.mutedText }}>{n.description}</div></div>{i < list.length - 1 && <div className="text-2xl font-black" style={{ color: theme.border }}>→</div>}</React.Fragment>)}</div></Shell>;
}
export function ExecutiveTimeline({ visual, theme = defaultTheme }: { visual: ExecutiveStructuredVisual; theme?: ExecutiveDesignTokens }) { return <Shell title="Timeline" theme={theme}><div className="relative mt-8 flex justify-between border-t-4 pt-6" style={{ borderColor: theme.border }}>{items(visual).slice(0, 5).map((n, i) => <div key={n.id || i} className="w-1/5 pr-3"><div className="-mt-10 mb-4 h-5 w-5 rounded-full ring-4" style={{ background: theme.chart[i % theme.chart.length], '--tw-ring-color': theme.surface } as React.CSSProperties} /><div className="text-sm font-black">{n.label}</div><div className="text-xs font-semibold" style={{ color: theme.mutedText }}>{n.description}</div></div>)}</div></Shell>; }
export function ExecutiveDependencyMap({ visual, theme = defaultTheme }: { visual: ExecutiveStructuredVisual; theme?: ExecutiveDesignTokens }) { return <Shell title="Dependency map" theme={theme}><div className="grid h-full grid-cols-3 gap-3">{items(visual).slice(0, 6).map((n, i) => <div key={n.id || i} className="rounded-2xl p-4 ring-1" style={panelStyle(theme)}><div className="mb-2 h-2 w-10 rounded-full" style={{ background: theme.chart[i % theme.chart.length] }} /><div className="text-sm font-black">{n.label}</div><div className="text-xs" style={{ color: theme.mutedText }}>{n.description}</div></div>)}</div></Shell>; }
export function ExecutiveRiskMatrix({ visual, theme = defaultTheme }: { visual: ExecutiveStructuredVisual; theme?: ExecutiveDesignTokens }) { return <Shell title="Risk matrix" theme={theme}><div className="grid h-[90%] grid-cols-2 grid-rows-2 gap-3">{['Monitor', 'Mitigate', 'Accept', 'Escalate'].map((label, i) => <div key={label} className="rounded-2xl border p-4" style={panelStyle(theme, i === 3 ? 'risk' : undefined)}><div className="text-xs font-black uppercase" style={{ color: i === 3 ? theme.risk : theme.mutedText }}>{label}</div><div className="mt-3 text-sm font-black">{items(visual)[i]?.label || 'Risk area'}</div><div className="text-xs" style={{ color: theme.mutedText }}>{items(visual)[i]?.description}</div></div>)}</div></Shell>; }
export function ExecutiveMetricDashboard({ visual, theme = defaultTheme }: { visual: ExecutiveStructuredVisual; theme?: ExecutiveDesignTokens }) { const m = visual.metrics?.length ? visual.metrics : items(visual).map((n, i) => ({ label: n.label, value: `${80 - i * 9}%`, description: n.description })); return <Shell title="Metric dashboard" theme={theme}><div className="grid h-full grid-cols-2 gap-3">{m.slice(0, 4).map((x, i) => <div key={i} className="rounded-2xl p-5" style={panelStyle(theme)}><div className="text-3xl font-black" style={{ color: theme.chart[i % theme.chart.length] }}>{x.value}</div><div className="text-sm font-black">{x.label}</div><div className="text-xs" style={{ color: theme.mutedText }}>{x.description}</div></div>)}</div></Shell>; }
export function ExecutiveHierarchy({ visual, theme = defaultTheme }: { visual: ExecutiveStructuredVisual; theme?: ExecutiveDesignTokens }) { return <Shell title="Hierarchy" theme={theme}><div className="flex h-full flex-col items-center justify-center gap-3">{items(visual).slice(0, 5).map((n, i) => <div key={n.id || i} className="rounded-2xl p-3 text-center text-sm font-black text-white" style={{ background: theme.chart[i % theme.chart.length], width: `${95 - i * 12}%` }}>{n.label}</div>)}</div></Shell>; }
export function ExecutiveEcosystemMap({ visual, theme = defaultTheme }: { visual: ExecutiveStructuredVisual; theme?: ExecutiveDesignTokens }) { return <Shell title="Ecosystem map" theme={theme}><div className="relative h-[92%]"><div className="absolute left-1/2 top-1/2 grid h-28 w-28 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full text-center text-xs font-black" style={{ backgroundColor: theme.text, color: theme.isLight ? theme.surface : '#0F172A' }}>Core model</div>{items(visual).slice(0, 6).map((n, i) => <div key={n.id || i} className="absolute rounded-2xl p-3 text-xs font-bold ring-1" style={{ ...panelStyle(theme), left: `${i % 2 ? 62 : 8}%`, top: `${12 + (i % 3) * 28}%` }}>{n.label}</div>)}</div></Shell>; }
export function ExecutiveComparison({ visual, theme = defaultTheme }: { visual: ExecutiveStructuredVisual; theme?: ExecutiveDesignTokens }) { return <Shell title="Comparison" theme={theme}><div className="grid h-full grid-cols-2 gap-4">{items(visual).slice(0, 2).map((n, i) => <div key={n.id || i} className="rounded-3xl p-5" style={panelStyle(theme)}><div className="mb-3 text-xs font-black uppercase" style={{ color: theme.chart[i % theme.chart.length] }}>{i ? 'Option B' : 'Option A'}</div><div className="text-xl font-black">{n.label}</div><div className="mt-2 text-sm font-semibold" style={{ color: theme.mutedText }}>{n.description}</div></div>)}</div></Shell>; }

export function ExecutiveStructuredVisualRenderer({ visual, className, theme = defaultTheme }: { visual?: ExecutiveStructuredVisual; className?: string; theme?: ExecutiveDesignTokens }) {
  if (!visual) return null;
  const props = { visual, theme };
  return <div className={className} data-executive-structured-visual={visual.type}>{visual.type === 'timeline' ? <ExecutiveTimeline {...props} /> : visual.type === 'dependency-map' ? <ExecutiveDependencyMap {...props} /> : visual.type === 'risk-matrix' ? <ExecutiveRiskMatrix {...props} /> : visual.type === 'metric-dashboard' ? <ExecutiveMetricDashboard {...props} /> : visual.type === 'hierarchy' ? <ExecutiveHierarchy {...props} /> : visual.type === 'ecosystem-map' ? <ExecutiveEcosystemMap {...props} /> : visual.type === 'comparison' ? <ExecutiveComparison {...props} /> : <ExecutiveProcessFlow {...props} />}</div>;
}
